//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="MultistreamConferenceServiceConfiguration")]
[System.Xml.Serialization.XmlRootAttribute("MultistreamConferenceConfiguration", Namespace="MultistreamConferenceServiceConfiguration", IsNullable=false)]
public partial class MultistreamConferenceConfigurationType {
    
    private string dbFileNameField;
    
    private string serviceHostUrlField;
    
    private TimeSpanType sessionTimeoutField;
    
    private TimeSpanType tokenTimeoutField;
    
    private TimeSpanType deliveryTimeoutField;
    
    private SmtpConfigurationType smtpField;
    
    private string logsDirPathField;
    
    private MultistreamConferenceLinkTemplatesType linkTemplatesField;
    
    /// <remarks/>
    public string DbFileName {
        get {
            return this.dbFileNameField;
        }
        set {
            this.dbFileNameField = value;
        }
    }
    
    /// <remarks/>
    public string ServiceHostUrl {
        get {
            return this.serviceHostUrlField;
        }
        set {
            this.serviceHostUrlField = value;
        }
    }
    
    /// <remarks/>
    public TimeSpanType SessionTimeout {
        get {
            return this.sessionTimeoutField;
        }
        set {
            this.sessionTimeoutField = value;
        }
    }
    
    /// <remarks/>
    public TimeSpanType TokenTimeout {
        get {
            return this.tokenTimeoutField;
        }
        set {
            this.tokenTimeoutField = value;
        }
    }
    
    /// <remarks/>
    public TimeSpanType DeliveryTimeout {
        get {
            return this.deliveryTimeoutField;
        }
        set {
            this.deliveryTimeoutField = value;
        }
    }
    
    /// <remarks/>
    public SmtpConfigurationType Smtp {
        get {
            return this.smtpField;
        }
        set {
            this.smtpField = value;
        }
    }
    
    /// <remarks/>
    public string LogsDirPath {
        get {
            return this.logsDirPathField;
        }
        set {
            this.logsDirPathField = value;
        }
    }
    
    /// <remarks/>
    public MultistreamConferenceLinkTemplatesType LinkTemplates {
        get {
            return this.linkTemplatesField;
        }
        set {
            this.linkTemplatesField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="MultistreamConferenceServiceConfiguration")]
public partial class TimeSpanType {
    
    private int daysField;
    
    private bool daysFieldSpecified;
    
    private int hoursField;
    
    private bool hoursFieldSpecified;
    
    private int minutesField;
    
    private bool minutesFieldSpecified;
    
    private int secondsField;
    
    private bool secondsFieldSpecified;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int Days {
        get {
            return this.daysField;
        }
        set {
            this.daysField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool DaysSpecified {
        get {
            return this.daysFieldSpecified;
        }
        set {
            this.daysFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int Hours {
        get {
            return this.hoursField;
        }
        set {
            this.hoursField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool HoursSpecified {
        get {
            return this.hoursFieldSpecified;
        }
        set {
            this.hoursFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int Minutes {
        get {
            return this.minutesField;
        }
        set {
            this.minutesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool MinutesSpecified {
        get {
            return this.minutesFieldSpecified;
        }
        set {
            this.minutesFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int Seconds {
        get {
            return this.secondsField;
        }
        set {
            this.secondsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool SecondsSpecified {
        get {
            return this.secondsFieldSpecified;
        }
        set {
            this.secondsFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="MultistreamConferenceServiceConfiguration")]
public partial class MultistreamConferenceLinkTemplatesType {
    
    private string activationLinkField;
    
    private string passwordRestoreLinkField;
    
    /// <remarks/>
    public string ActivationLink {
        get {
            return this.activationLinkField;
        }
        set {
            this.activationLinkField = value;
        }
    }
    
    /// <remarks/>
    public string PasswordRestoreLink {
        get {
            return this.passwordRestoreLinkField;
        }
        set {
            this.passwordRestoreLinkField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="MultistreamConferenceServiceConfiguration")]
public partial class SmtpConfigurationType {
    
    private string smtpServerHostField;
    
    private int smtpServerPortField;
    
    private bool smtpServerPortFieldSpecified;
    
    private string smtpLoginField;
    
    private string smtpPasswordField;
    
    private bool smtpUseSslField;
    
    private bool smtpUseSslFieldSpecified;
    
    private bool smtpUseDefaultCredentialsField;
    
    private bool smtpUseDefaultCredentialsFieldSpecified;
    
    private string smtpPickupDirectoryLocationField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string SmtpServerHost {
        get {
            return this.smtpServerHostField;
        }
        set {
            this.smtpServerHostField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int SmtpServerPort {
        get {
            return this.smtpServerPortField;
        }
        set {
            this.smtpServerPortField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool SmtpServerPortSpecified {
        get {
            return this.smtpServerPortFieldSpecified;
        }
        set {
            this.smtpServerPortFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string SmtpLogin {
        get {
            return this.smtpLoginField;
        }
        set {
            this.smtpLoginField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string SmtpPassword {
        get {
            return this.smtpPasswordField;
        }
        set {
            this.smtpPasswordField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool SmtpUseSsl {
        get {
            return this.smtpUseSslField;
        }
        set {
            this.smtpUseSslField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool SmtpUseSslSpecified {
        get {
            return this.smtpUseSslFieldSpecified;
        }
        set {
            this.smtpUseSslFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool SmtpUseDefaultCredentials {
        get {
            return this.smtpUseDefaultCredentialsField;
        }
        set {
            this.smtpUseDefaultCredentialsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool SmtpUseDefaultCredentialsSpecified {
        get {
            return this.smtpUseDefaultCredentialsFieldSpecified;
        }
        set {
            this.smtpUseDefaultCredentialsFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string SmtpPickupDirectoryLocation {
        get {
            return this.smtpPickupDirectoryLocationField;
        }
        set {
            this.smtpPickupDirectoryLocationField = value;
        }
    }
}
