//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="MultistreamConferenceService")]
[System.Xml.Serialization.XmlRootAttribute("Ok", Namespace="MultistreamConferenceService", IsNullable=false)]
public partial class OkType {
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="MultistreamConferenceService")]
public partial class GraphEntityInfo {
    
    private GraphEntityInfoField[] fieldsField;
    
    private string idField;
    
    private string kindField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("Field", IsNullable=false)]
    public GraphEntityInfoField[] Fields {
        get {
            return this.fieldsField;
        }
        set {
            this.fieldsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Kind {
        get {
            return this.kindField;
        }
        set {
            this.kindField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="MultistreamConferenceService")]
public partial class GraphEntityInfoField {
    
    private GraphEntityInfo[] itemsField;
    
    private string nameField;
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Entity")]
    public GraphEntityInfo[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="MultistreamConferenceService")]
public partial class StampType {
    
    private long ticksField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public long Ticks {
        get {
            return this.ticksField;
        }
        set {
            this.ticksField = value;
        }
    }
}

/// <remarks/>
[System.Xml.Serialization.XmlIncludeAttribute(typeof(ConferenceCreationResponse))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(ConferenceInfoType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(UserInfoType))]
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="MultistreamConferenceService")]
public abstract partial class InfoType {
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="MultistreamConferenceService")]
public partial class ConferenceCreationResponse : InfoType {
    
    private string roomIdField;
    
    /// <remarks/>
    public string RoomId {
        get {
            return this.roomIdField;
        }
        set {
            this.roomIdField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="MultistreamConferenceService")]
public partial class UserInfoType : InfoType {
    
    private long idField;
    
    private string nameField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public long Id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="MultistreamConferenceService")]
[System.Xml.Serialization.XmlRootAttribute("RegisterSpec", Namespace="MultistreamConferenceService", IsNullable=false)]
public partial class RegisterSpecType {
    
    private string loginField;
    
    private string passwordField;
    
    private string emailField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Login {
        get {
            return this.loginField;
        }
        set {
            this.loginField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Password {
        get {
            return this.passwordField;
        }
        set {
            this.passwordField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Email {
        get {
            return this.emailField;
        }
        set {
            this.emailField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="MultistreamConferenceService")]
[System.Xml.Serialization.XmlRootAttribute("RequestActivationSpec", Namespace="MultistreamConferenceService", IsNullable=false)]
public partial class RequestActivationSpecType {
    
    private string emailField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Email {
        get {
            return this.emailField;
        }
        set {
            this.emailField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="MultistreamConferenceService")]
[System.Xml.Serialization.XmlRootAttribute("ChangePasswordSpec", Namespace="MultistreamConferenceService", IsNullable=false)]
public partial class ChangePasswordSpecType {
    
    private string newPasswordField;
    
    private string emailField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string NewPassword {
        get {
            return this.newPasswordField;
        }
        set {
            this.newPasswordField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Email {
        get {
            return this.emailField;
        }
        set {
            this.emailField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="MultistreamConferenceService")]
[System.Xml.Serialization.XmlRootAttribute("ChangeEmailSpec", Namespace="MultistreamConferenceService", IsNullable=false)]
public partial class ChangeEmailSpecType {
    
    private string passwordField;
    
    private string oldEmailField;
    
    private string newEmailField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Password {
        get {
            return this.passwordField;
        }
        set {
            this.passwordField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string OldEmail {
        get {
            return this.oldEmailField;
        }
        set {
            this.oldEmailField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string NewEmail {
        get {
            return this.newEmailField;
        }
        set {
            this.newEmailField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="MultistreamConferenceService")]
[System.Xml.Serialization.XmlRootAttribute("ResetPasswordSpec", Namespace="MultistreamConferenceService", IsNullable=false)]
public partial class ResetPasswordSpecType {
    
    private string loginField;
    
    private string emailField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Login {
        get {
            return this.loginField;
        }
        set {
            this.loginField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Email {
        get {
            return this.emailField;
        }
        set {
            this.emailField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="MultistreamConferenceService")]
[System.Xml.Serialization.XmlRootAttribute("LoginSpec", Namespace="MultistreamConferenceService", IsNullable=false)]
public partial class LoginSpecType {
    
    private string loginField;
    
    private string passwordField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Login {
        get {
            return this.loginField;
        }
        set {
            this.loginField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Password {
        get {
            return this.passwordField;
        }
        set {
            this.passwordField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="MultistreamConferenceService")]
[System.Xml.Serialization.XmlRootAttribute("ProfileFootprintInfo", Namespace="MultistreamConferenceService", IsNullable=false)]
public partial class ProfileFootprintInfoType {
    
    private string loginField;
    
    private string emailFootprintField;
    
    private bool isActivatedField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Login {
        get {
            return this.loginField;
        }
        set {
            this.loginField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string EmailFootprint {
        get {
            return this.emailFootprintField;
        }
        set {
            this.emailFootprintField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool IsActivated {
        get {
            return this.isActivatedField;
        }
        set {
            this.isActivatedField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="MultistreamConferenceService")]
[System.Xml.Serialization.XmlRootAttribute("ConferenceInfo", Namespace="MultistreamConferenceService", IsNullable=false)]
public partial class ConferenceInfoType : InfoType {
    
    private string titleField;
    
    private string descriptionField;
    
    private ConferenceStateKindType stateField;
    
    private StampType stateStampField;
    
    private StampType creationStampField;
    
    private StampType startStampField;
    
    private StampType endStampField;
    
    private int participantsField;
    
    private string idField;
    
    /// <remarks/>
    public string Title {
        get {
            return this.titleField;
        }
        set {
            this.titleField = value;
        }
    }
    
    /// <remarks/>
    public string Description {
        get {
            return this.descriptionField;
        }
        set {
            this.descriptionField = value;
        }
    }
    
    /// <remarks/>
    public ConferenceStateKindType State {
        get {
            return this.stateField;
        }
        set {
            this.stateField = value;
        }
    }
    
    /// <remarks/>
    public StampType StateStamp {
        get {
            return this.stateStampField;
        }
        set {
            this.stateStampField = value;
        }
    }
    
    /// <remarks/>
    public StampType CreationStamp {
        get {
            return this.creationStampField;
        }
        set {
            this.creationStampField = value;
        }
    }
    
    /// <remarks/>
    public StampType StartStamp {
        get {
            return this.startStampField;
        }
        set {
            this.startStampField = value;
        }
    }
    
    /// <remarks/>
    public StampType EndStamp {
        get {
            return this.endStampField;
        }
        set {
            this.endStampField = value;
        }
    }
    
    /// <remarks/>
    public int Participants {
        get {
            return this.participantsField;
        }
        set {
            this.participantsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="MultistreamConferenceService")]
public enum ConferenceStateKindType {
    
    /// <remarks/>
    Scheduled,
    
    /// <remarks/>
    Running,
    
    /// <remarks/>
    Finished,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="MultistreamConferenceService")]
[System.Xml.Serialization.XmlRootAttribute("List", Namespace="MultistreamConferenceService", IsNullable=false)]
public partial class ListType {
    
    private InfoType[] itemsField;
    
    private long totalCountField;
    
    private long fromField;
    
    private long countField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ConferenceInfo", typeof(ConferenceInfoType))]
    [System.Xml.Serialization.XmlElementAttribute("UserInfo", typeof(UserInfoType))]
    public InfoType[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public long TotalCount {
        get {
            return this.totalCountField;
        }
        set {
            this.totalCountField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public long From {
        get {
            return this.fromField;
        }
        set {
            this.fromField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public long Count {
        get {
            return this.countField;
        }
        set {
            this.countField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="MultistreamConferenceService")]
[System.Xml.Serialization.XmlRootAttribute("AnalysisJobImmediateQueryCommand", Namespace="MultistreamConferenceService", IsNullable=false)]
public partial class AnalysisJobImmediateQueryCommandInfoType {
    
    private string textField;
    
    private bool isGremlinField;
    
    /// <remarks/>
    public string Text {
        get {
            return this.textField;
        }
        set {
            this.textField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool IsGremlin {
        get {
            return this.isGremlinField;
        }
        set {
            this.isGremlinField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="MultistreamConferenceService")]
[System.Xml.Serialization.XmlRootAttribute("AnalysisJobImmediateQueryResult", Namespace="MultistreamConferenceService", IsNullable=false)]
public partial class AnalysisJobImmediateQueryResultInfoType {
    
    private AnalysisJobImmediateQueryCommandInfoType commandField;
    
    private GraphEntityInfo[] resultField;
    
    /// <remarks/>
    public AnalysisJobImmediateQueryCommandInfoType Command {
        get {
            return this.commandField;
        }
        set {
            this.commandField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("Entity", IsNullable=false)]
    public GraphEntityInfo[] Result {
        get {
            return this.resultField;
        }
        set {
            this.resultField = value;
        }
    }
}

/// <remarks/>
[System.Xml.Serialization.XmlIncludeAttribute(typeof(ExtendedErrorInfoType))]
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="MultistreamConferenceService")]
[System.Xml.Serialization.XmlRootAttribute("ErrorInfo", Namespace="MultistreamConferenceService", IsNullable=false)]
public partial class ErrorInfoType {
    
    private string messageField;
    
    private string stackTraceField;
    
    private ErrorInfoType innerErrorField;
    
    private string typeNameField;
    
    /// <remarks/>
    public string Message {
        get {
            return this.messageField;
        }
        set {
            this.messageField = value;
        }
    }
    
    /// <remarks/>
    public string StackTrace {
        get {
            return this.stackTraceField;
        }
        set {
            this.stackTraceField = value;
        }
    }
    
    /// <remarks/>
    public ErrorInfoType InnerError {
        get {
            return this.innerErrorField;
        }
        set {
            this.innerErrorField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string TypeName {
        get {
            return this.typeNameField;
        }
        set {
            this.typeNameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="MultistreamConferenceService")]
public partial class ExtendedErrorInfoType : ErrorInfoType {
    
    private string rawErrorInfoField;
    
    /// <remarks/>
    public string RawErrorInfo {
        get {
            return this.rawErrorInfoField;
        }
        set {
            this.rawErrorInfoField = value;
        }
    }
}
